### ISSUE TITLE
"Mesh Type 1 Unimplemented"

### ISSUE THREAD

**Issue by Casuallynoted** [Dragorn421/zelda64-import-blender#3]
Hello! I'm currently using this tool to extract files from the recently leaked prototype maps. While most maps load, some of them provide errors about headers, notably the error I've put in the title. I've attached the archive containing the full set of map files, but the maps that are having this issue are 20, 41 and 48 (among a few others). Other maps such as Gerudo Valley import somewhat correctly but with missing vertices and a "Found Empty Tri!" error. A good example of this is map 22.
[scene.zip](https://github.com/Dragorn421/zelda64-import-blender/files/5863022/scene.zip)

**Comment by Dragorn421** [comment]
Hello, I'm staying away from leaked data for legal reasons (I am involved in the OoT decomp project) so I won't look at your files, sorry. Also sorry for the late reply, I've been away from the internet.

However I believe I can still help you.

"Mesh Type 1" means the scene uses pre-rendered backgrounds, like the Hyrule market. ( https://wiki.cloudmodding.com/oot/Scenes_and_Rooms#Type_1 )
It had limited support in an older version of the script (try it maybe: https://github.com/Dragorn421/zelda64-import-blender/blob/66972cd2397d18760794ab01e0b1249d55a19a58/io_import_z64.py ), at best it will only get you geometry (no textures) that I believe are used for culling only (eg so Link doesn't get drawn in front of a tree in the background image)

No released version of this script can get you the JFIF (jpeg basically) images that are used but you can get to them using the cloudmodding documentation I linked. I believe I worked on automating it months ago, let me know if you're interested I may polish it up and release it.

EDIT: oh and drop in the zelda modding discord Hylian Modding if you haven't already, there should be plenty helpful people there

**Comment by Dragorn421** [comment]
Fixed by 917e76d606589682205e435a506424065df8df02
